[mypy]
files = src/issues
mypy_path = $MYPY_CONFIG_FILE_DIR/tests/_demoapp
;enable_error_code =
;    deprecated,
;    ignore-without-code
plugins =
    mypy_django_plugin.main

strict = true



[mypy.plugins.django-stubs]
django_settings_module = demo.settings

[mypy-azure.*]
ignore_errors = true
ignore_missing_imports = True

[mypy-gitlab.*]
ignore_errors = true
ignore_missing_imports = True

[mypy-github.*]
ignore_errors = true
ignore_missing_imports = True

[mypy-msrest.*]
ignore_errors = true
ignore_missing_imports = True
