[tox]
requires =
    tox>=4.2
    tox-uv>=1.25
env_list =
    lint
    d52-py313
    d42-py310
    mypy
    docs
    pkg_meta

[testenv]
description = run tests
deps =
    d32: django==3.2.*
    d42: django==4.2.*
    d52: django==5.2.*
extras =
    github
    gitlab
pass_env =
    CI
    DATABASE_URL
set_env =
    DEVOPS_PROJECT = org/project
    DEVOPS_TOKEN = token
    GITHUB_API_TOKEN = token
    GITHUB_PROJECT = org/project
    GITLAB_API_TOKEN = token
    GITLAB_PROJECT = org/project
    PYTHONDONTWRITEBYTECODE = 1
    PYTHONWARNINGS = ignore::DeprecationWarning
commands =
    {posargs:pytest tests -rw --headless --cov-report=xml  --junit-xml=junit.xml -o junit_family=legacy}
dependency_groups = dev

[testenv:lint]
description = run static analysis and style check using ruff
skip_install = true
deps =
    pre-commit-uv>=4.1.1
commands =
    pre-commit run --all-files --show-diff-on-failure
dependency_groups = dev

[testenv:mypy]
runner = uv-venv-lock-runner
description = run mypy type checking
skip_install = false
commands =
    mypy --config-file mypy.ini {posargs:}
dependency_groups = type-check
uv_sync_flags = --no-editable

[testenv:docs]
description = build mkdocs documentation
skip_install = false
deps =
commands =
    mkdocs build {posargs:}
dependency_groups = docs

[testenv:pkg_meta]
runner = uv-venv-lock-runner
description = check that python package
skip_install = true
deps =
    check-wheel-contents>=0.6
    twine>=5.1.1
    uv>=0.5
commands =
    uv build --sdist -q --out-dir {env_tmp_dir} .
    uvx twine check {env_tmp_dir}{/}*
    uvx check-wheel-contents --ignore W002,W004,W009,W004 {env_tmp_dir}
    uv pip install --no-binary django-online-issues --find-links {env_tmp_dir} django-online-issues

[testenv:d32-type]
commands =
    {[type]commands}
base = type

[testenv:d42-type]
commands =
    {[type]commands}
base = type

[testenv:d52-type]
commands =
    {[type]commands}
base = type

[type]
description = run type check on code base
commands =
    mypy --config-file mypy.ini {posargs:}
deps =
    d42: django==4.2.*
    d52: django==5.2.*
dependency_groups =
    dev
    d42: type-check
    d52: type-check
